FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

WORKDIR /app

# ViennaRNA and RNAstructure will be installed here
# in a later project stage.

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .